name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - run: echo "Lê Quang Phú"
    - run: echo "Lê Quang Phú 1"
